# This file is part of khmer, https://github.com/dib-lab/khmer/, and is
# Copyright (C) 2015, Michigan State University.
# Copyright (C) 2015-2016, The Regents of the University of California.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#
#     * Neither the name of the Michigan State University nor the names
#       of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written
#       permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Contact: khmer-project@idyll.org

KHMER=..

KSIZE= 30
HASH_SIZE= 4e8
N_HASHES= 4

all: estimated_probabilities.${KSIZE}.json

my_mock.fa:
	wget https://github.com/dib-lab/khmer-testdata/raw/master/my_mock.fa

%.fastq.gz:
	wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR172/SRR172903/SRR172903.fastq.gz
	wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR172/SRR172902/SRR172902.fastq.gz

combined_reads.ht: SRR172902.fastq.gz SRR172903.fastq.gz
	python $(KHMER)/scripts/load-into-counting.py --ksize $(KSIZE) \
		-x $(HASH_SIZE) -N $(N_HASHES) $@ $^

my_mock.1.bt1: my_mock.fa
	bowtie2-build my_mock.fa my_mock

combined_reads_mapping.bam: SRR172902.fastq.gz SRR172903.fastq.gz my_mock.1.bt1
	bowtie2 -x my_mock -U SRR172902.fastq.gz -U SRR172903.fastq.gz \
		| samtools view -S -F4 -b - > combined_reads_mapping.bam

estimated_probabilities.$(KSIZE).json: combined_reads.ht combined_reads_mapping.bam
	python readaligner_pairhmm_train.py --json combined_reads.ht \
		combined_reads_mapping.bam \
		> estimated_probabilities.${KSIZE}.json
