#! /usr/bin/env python
# This file is part of khmer, https://github.com/dib-lab/khmer/, and is
# Copyright (C) 2015, The Regents of the University of California.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#
#     * Neither the name of the Michigan State University nor the names
#       of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written
#       permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Contact: khmer-project@idyll.org

# Magic descriptions of khmer file types for file(1) command.
# Format is described in magic(5).
#
# Example:
#
# $ file --magic-file lib/magic tests/test-data/normC20k20.ct
# tests/test-data/normC20k20.ct: Binary from the khmer project, file format version 4, k-mer countgraph
#
# $ file --magic-file lib/magic --mime-type tests/test-data/normC20k20.ct
# tests/test-data/normC20k20.ct: application/vnd.oxli.countgraph
#
# $ file --magic-file lib/magic --extension tests/test-data/normC20k20.ct
# tests/test-data/normC20k20.ct: oxlicg
#
# See also:
# http://www.iana.org/assignments/media-types/application/vnd.oxli.countgraph

0 string OXLI Binary from the khmer project,
>4 byte x file format version %u,
>5 byte 1 k-mer countgraph
!:ext oxlicg
!:mime application/vnd.oxli.countgraph
>5 byte 2 k-mer nodegraph
!:ext oxling
>5 byte 3 k-mer tagset
!:ext oxlits
>5 byte 4 k-mer partition stoptags
!:ext oxlist
>5 byte 5 k-mer partition subset
!:ext oxliss
>5 byte 6 k-mer graphlabels
!:ext oxligl
