#!/usr/bin/env python
#
# This file is a part of khmer, http://github.com/ged-lab/khmer/, and is
# Copyright (C) The Regents of the University of California, 2015. It is
# licensed under the three-clause BSD license; see doc/LICENSE.txt.
# Contact: khmer-project@idyll.org
#

if __name__ == '__main__':
   import oxli
   oxli.main()
